export const headers = [
  { ignore: false, cell: "Sample ID", sql: "external_number" },
  { ignore: false, cell: "Fecha", sql: "samping_date" },
  { ignore: false, cell: "Fecha de Recepción", sql: "withdraw_date" },
  { ignore: false, cell: "Informar Fecha de Aviso", sql: "proposed_date" },
  { ignore: false, cell: "Cliente", sql: "client" },
  { ignore: false, cell: "Faena", sql: "site" },
  // IGNORE
  { ignore: true, cell: "Contrato", sql: "Contrato" },
  { ignore: false, cell: "Tipo de Equipo", sql: "machine_type" },
  { ignore: false, cell: "Equipo", sql: "machine" },
  { ignore: false, cell: "Código Equipo" },
  { ignore: false, cell: "Descripcion Componente", sql: "component" },
  { ignore: false, cell: "Tipo de Componente", sql: "component_type" },
  { ignore: false, cell: "Código Componente" },
  { ignore: false, cell: "Tag", sql: "tag" },
  // IGNORE
  { ignore: true, cell: "Muestra", sql: "Muestra" },
  { ignore: false, cell: "Aceite", sql: "lubricant" },
  {
    ignore: false,
    cell: "Diagnóstico/Recomendaciones",
    sql: "recommendation",
  },
  { ignore: false, cell: "Código de Alarma", sql: "id_sample_condition" },
  { ignore: false, cell: "Tipo Anomalía", sql: "id_anomaly_type" },
  { ignore: false, cell: "Estado Seguimiento", sql: "id_tracking_state" },
  {
    ignore: false,
    cell: "Tiempo/Distancia de Operación del Equipo",
    sql: "machine_continuity",
  },
  {
    ignore: false,
    cell: "Tiempo/Distancia de Uso del Aceite",
    sql: "lubricant_continuity",
  },
  // Essays
  { ignore: false, cell: "Relleno", sql: -1 },
  { ignore: false, cell: "Agua", sql: 26 },
  { ignore: false, cell: "Oxi", sql: 31 },
  { ignore: false, cell: "Hollin", sql: 55 },
  { ignore: false, cell: "Nit", sql: 33 },
  // IGNORE
  { ignore: true, cell: "Antiwear", sql: -1 },
  // IGNORE
  // { ignore: true, cell: "D.F.", sql: -1 },
  { ignore: false, cell: "Sulfate", sql: 32 },
  { ignore: false, cell: "Gly", sql: 58 },
  // IGNORE
  // { ignore: true, cell: "Gasoline", sql: -1 },
  { ignore: false, cell: "TBN", sql: 27 },
  { ignore: false, cell: "TAN", sql: 28 },
  { ignore: false, cell: "Combustible", sql: 30 },
  { ignore: false, cell: "V40", sql: 23 },
  // IGNORE
  { ignore: true, cell: "ISO(>4µm)", sql: -1 },
  // IGNORE
  { ignore: true, cell: "ISO(>6µm)", sql: -1 },
  // IGNORE
  { ignore: true, cell: "ISO(>14µm)", sql: -1 },
  { ignore: false, cell: "ISO 4406/99", sql: 47 },
  { ignore: false, cell: ">4µm", sql: 44 },
  { ignore: false, cell: ">6µm", sql: 45 },
  { ignore: false, cell: ">14µm", sql: 46 },
  { ignore: false, cell: "PQ", sql: 29 },
  { ignore: false, cell: "V100", sql: 24 },
  { ignore: false, cell: "Fe", sql: 1 },
  { ignore: false, cell: "Cr", sql: 2 },
  { ignore: false, cell: "Ni", sql: 6 },
  { ignore: false, cell: "Mo", sql: 20 },
  { ignore: false, cell: "Al", sql: 3 },
  { ignore: false, cell: "Pb", sql: 5 },
  { ignore: false, cell: "Cu", sql: 4 },
  { ignore: false, cell: "Sn", sql: 8 },
  { ignore: false, cell: "Ti", sql: 9 },
  { ignore: false, cell: "Ag", sql: 7 },
  { ignore: false, cell: "Ca", sql: 19 },
  { ignore: false, cell: "Mg", sql: 21 },
  { ignore: false, cell: "P", sql: 22 },
  { ignore: false, cell: "Zn", sql: 16 },
  { ignore: false, cell: "Ba", sql: 17 },
  { ignore: false, cell: "B", sql: 18 },
  { ignore: false, cell: "Si", sql: 15 },
  { ignore: false, cell: "Na", sql: 13 },
  { ignore: false, cell: "V", sql: 10 },
  // IGNORE
  // { ignore: true, cell: "H", sql: -1 },
  { ignore: false, cell: "K", sql: 14 },
  { ignore: false, cell: "Cd", sql: 11 },
  { ignore: false, cell: "Mn", sql: 12 },
];
